-- INSERTING into CRB_LANGUAGE
Insert into CRB_LANGUAGE (CODE,NAME) values ('AA','AFAR');
Insert into CRB_LANGUAGE (CODE,NAME) values ('AAR','AFAR');
Insert into CRB_LANGUAGE (CODE,NAME) values ('AB','ABKHAZIAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('ABK','ABKHAZIAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('ACE','ACHINESE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('ACH','ACOLI');
Insert into CRB_LANGUAGE (CODE,NAME) values ('ADA','ADANGME');
Insert into CRB_LANGUAGE (CODE,NAME) values ('AE','AVESTAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('AF','AFRIKAANS');
Insert into CRB_LANGUAGE (CODE,NAME) values ('AFA','AFRO-ASIATIC (OTHER)');
Insert into CRB_LANGUAGE (CODE,NAME) values ('AFH','AFRIHILI');
Insert into CRB_LANGUAGE (CODE,NAME) values ('AFR','AFRIKAANS');
Insert into CRB_LANGUAGE (CODE,NAME) values ('AJM','ALJAMIA');
Insert into CRB_LANGUAGE (CODE,NAME) values ('AK','AKAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('AKA','AKAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('AKK','AKKADIAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('ALB','ALBANIAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('ALE','ALEUT');
Insert into CRB_LANGUAGE (CODE,NAME) values ('ALG','ALGONQUIAN LANGUAGES');
Insert into CRB_LANGUAGE (CODE,NAME) values ('AM','AMHARIC');
Insert into CRB_LANGUAGE (CODE,NAME) values ('AMH','AMHARIC');
Insert into CRB_LANGUAGE (CODE,NAME) values ('AN','ARAGONESE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('ANG','ENGLISH, OLD (CA. 450-1100)');
Insert into CRB_LANGUAGE (CODE,NAME) values ('APA','APACHE LANGUAGES');
Insert into CRB_LANGUAGE (CODE,NAME) values ('AR','ARABIC');
Insert into CRB_LANGUAGE (CODE,NAME) values ('ARA','ARABIC');
Insert into CRB_LANGUAGE (CODE,NAME) values ('ARC','ARAMAIC');
Insert into CRB_LANGUAGE (CODE,NAME) values ('ARM','ARMENIAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('ARN','ARAUCANIAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('ARP','ARAPAHO');
Insert into CRB_LANGUAGE (CODE,NAME) values ('ART','ARTIFICIAL (OTHER)');
Insert into CRB_LANGUAGE (CODE,NAME) values ('ARW','ARAWAK');
Insert into CRB_LANGUAGE (CODE,NAME) values ('AS','ASSAMESE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('ASM','ASSAMESE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('ATH','ATHAPASCAN LANGUAGES');
Insert into CRB_LANGUAGE (CODE,NAME) values ('AUS','AUSTRALIAN LANGUAGES');
Insert into CRB_LANGUAGE (CODE,NAME) values ('AV','AVARIC');
Insert into CRB_LANGUAGE (CODE,NAME) values ('AVA','AVARIC');
Insert into CRB_LANGUAGE (CODE,NAME) values ('AVE','AVESTAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('AWA','AWADHI');
Insert into CRB_LANGUAGE (CODE,NAME) values ('AY','AYMARA');
Insert into CRB_LANGUAGE (CODE,NAME) values ('AYM','AYMARA');
Insert into CRB_LANGUAGE (CODE,NAME) values ('AZ','AZERBAIJANI');
Insert into CRB_LANGUAGE (CODE,NAME) values ('AZE','AZERBAIJANI');
Insert into CRB_LANGUAGE (CODE,NAME) values ('BA','BASHKIR');
Insert into CRB_LANGUAGE (CODE,NAME) values ('BAD','BANDA');
Insert into CRB_LANGUAGE (CODE,NAME) values ('BAI','BAMILEKE LANGUAGES');
Insert into CRB_LANGUAGE (CODE,NAME) values ('BAK','BASHKIR');
Insert into CRB_LANGUAGE (CODE,NAME) values ('BAL','BALUCHI');
Insert into CRB_LANGUAGE (CODE,NAME) values ('BAM','BAMBARA');
Insert into CRB_LANGUAGE (CODE,NAME) values ('BAN','BALINESE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('BAQ','BASQUE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('BAS','BASA');
Insert into CRB_LANGUAGE (CODE,NAME) values ('BAT','BALTIC (OTHER)');
Insert into CRB_LANGUAGE (CODE,NAME) values ('BE','BELARUSIAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('BEJ','BEJA');
Insert into CRB_LANGUAGE (CODE,NAME) values ('BEL','BELARUSIAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('BEM','BEMBA');
Insert into CRB_LANGUAGE (CODE,NAME) values ('BEN','BENGALI');
Insert into CRB_LANGUAGE (CODE,NAME) values ('BER','BERBER (OTHER)');
Insert into CRB_LANGUAGE (CODE,NAME) values ('BG','BULGARIAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('BH','BIHARI');
Insert into CRB_LANGUAGE (CODE,NAME) values ('BHO','BHOJPURI');
Insert into CRB_LANGUAGE (CODE,NAME) values ('BI','BISLAMA');
Insert into CRB_LANGUAGE (CODE,NAME) values ('BIH','BIHARI');
Insert into CRB_LANGUAGE (CODE,NAME) values ('BIK','BIKOL');
Insert into CRB_LANGUAGE (CODE,NAME) values ('BIN','BINI');
Insert into CRB_LANGUAGE (CODE,NAME) values ('BIS','BISLAMA');
Insert into CRB_LANGUAGE (CODE,NAME) values ('BLA','SIKSIKA');
Insert into CRB_LANGUAGE (CODE,NAME) values ('BM','BAMBARA');
Insert into CRB_LANGUAGE (CODE,NAME) values ('BN','BENGALI');
Insert into CRB_LANGUAGE (CODE,NAME) values ('BNT','BANTU (OTHER)');
Insert into CRB_LANGUAGE (CODE,NAME) values ('BO','TIBETAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('BOD','TIBETAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('BR','BRETON');
Insert into CRB_LANGUAGE (CODE,NAME) values ('BRA','BRAJ');
Insert into CRB_LANGUAGE (CODE,NAME) values ('BRE','BRETON');
Insert into CRB_LANGUAGE (CODE,NAME) values ('BS','BOSNIAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('BTK','BATAK (INDONESIA)');
Insert into CRB_LANGUAGE (CODE,NAME) values ('BUA','BURIAT');
Insert into CRB_LANGUAGE (CODE,NAME) values ('BUG','BUGINESE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('BUL','BULGARIAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('BUR','BURMESE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('CA','CATALAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('CAD','CADDO');
Insert into CRB_LANGUAGE (CODE,NAME) values ('CAI','CENTRAL AMERICAN INDIAN (OTHER)');
Insert into CRB_LANGUAGE (CODE,NAME) values ('CAR','CARIB');
Insert into CRB_LANGUAGE (CODE,NAME) values ('CAT','CATALAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('CAU','CAUCASIAN (OTHER)');
Insert into CRB_LANGUAGE (CODE,NAME) values ('CE','CHECHEN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('CEB','CEBUANO');
Insert into CRB_LANGUAGE (CODE,NAME) values ('CEL','CELTIC (OTHER)');
Insert into CRB_LANGUAGE (CODE,NAME) values ('CES','CZECH');
Insert into CRB_LANGUAGE (CODE,NAME) values ('CH','CHAMORRO');
Insert into CRB_LANGUAGE (CODE,NAME) values ('CHA','CHAMORRO');
Insert into CRB_LANGUAGE (CODE,NAME) values ('CHB','CHIBCHA');
Insert into CRB_LANGUAGE (CODE,NAME) values ('CHE','CHECHEN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('CHG','CHAGATAI');
Insert into CRB_LANGUAGE (CODE,NAME) values ('CHI','CHINESE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('CHK','CHUUKESE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('CHM','MARI');
Insert into CRB_LANGUAGE (CODE,NAME) values ('CHN','CHINOOK JARGON');
Insert into CRB_LANGUAGE (CODE,NAME) values ('CHO','CHOCTAW');
Insert into CRB_LANGUAGE (CODE,NAME) values ('CHP','CHIPEWYAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('CHR','CHEROKEE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('CHU','CHURCH SLAVIC');
Insert into CRB_LANGUAGE (CODE,NAME) values ('CHV','CHUVASH');
Insert into CRB_LANGUAGE (CODE,NAME) values ('CHY','CHEYENNE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('CMC','CHAMIC LANGUAGES');
Insert into CRB_LANGUAGE (CODE,NAME) values ('CO','CORSICAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('COP','COPTIC');
Insert into CRB_LANGUAGE (CODE,NAME) values ('COR','CORNISH');
Insert into CRB_LANGUAGE (CODE,NAME) values ('COS','CORSICAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('CPE','CREOLES AND PIDGINS, ENGLISH-BASED (OTHER)');
Insert into CRB_LANGUAGE (CODE,NAME) values ('CPF','CREOLES AND PIDGINS, FRENCH-BASED (OTHER)');
Insert into CRB_LANGUAGE (CODE,NAME) values ('CPP','CREOLES AND PIDGINS, PORTUGUESE-BASED (OTHER)');
Insert into CRB_LANGUAGE (CODE,NAME) values ('CR','CREE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('CRE','CREE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('CRP','CREOLES AND PIDGINS (OTHER)');
Insert into CRB_LANGUAGE (CODE,NAME) values ('CS','CZECH');
Insert into CRB_LANGUAGE (CODE,NAME) values ('CU','CHURCH SLAVIC');
Insert into CRB_LANGUAGE (CODE,NAME) values ('CUS','CUSHITIC (OTHER)');
Insert into CRB_LANGUAGE (CODE,NAME) values ('CV','CHUVASH');
Insert into CRB_LANGUAGE (CODE,NAME) values ('CY','WELSH');
Insert into CRB_LANGUAGE (CODE,NAME) values ('CYM','WELSH');
Insert into CRB_LANGUAGE (CODE,NAME) values ('CZE','CZECH');
Insert into CRB_LANGUAGE (CODE,NAME) values ('DA','DANISH');
Insert into CRB_LANGUAGE (CODE,NAME) values ('DAK','DAKOTA');
Insert into CRB_LANGUAGE (CODE,NAME) values ('DAN','DANISH');
Insert into CRB_LANGUAGE (CODE,NAME) values ('DAY','DAYAK');
Insert into CRB_LANGUAGE (CODE,NAME) values ('DE','GERMAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('DEL','DELAWARE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('DEN','SLAVE (ATHAPASCAN)');
Insert into CRB_LANGUAGE (CODE,NAME) values ('DEU','GERMAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('DGR','DOGRIB');
Insert into CRB_LANGUAGE (CODE,NAME) values ('DIN','DINKA');
Insert into CRB_LANGUAGE (CODE,NAME) values ('DIV','DIVEHI');
Insert into CRB_LANGUAGE (CODE,NAME) values ('DOI','DOGRI');
Insert into CRB_LANGUAGE (CODE,NAME) values ('DRA','DRAVIDIAN (OTHER)');
Insert into CRB_LANGUAGE (CODE,NAME) values ('DUA','DUALA');
Insert into CRB_LANGUAGE (CODE,NAME) values ('DUM','DUTCH, MIDDLE (CA. 1050-1350)');
Insert into CRB_LANGUAGE (CODE,NAME) values ('DUT','DUTCH');
Insert into CRB_LANGUAGE (CODE,NAME) values ('DV','DIVEHI');
Insert into CRB_LANGUAGE (CODE,NAME) values ('DYU','DYULA');
Insert into CRB_LANGUAGE (CODE,NAME) values ('DZ','DZONGKHA');
Insert into CRB_LANGUAGE (CODE,NAME) values ('DZO','DZONGKHA');
Insert into CRB_LANGUAGE (CODE,NAME) values ('EE','EWE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('EFI','EFIK');
Insert into CRB_LANGUAGE (CODE,NAME) values ('EGY','EGYPTIAN (ANCIENT)');
Insert into CRB_LANGUAGE (CODE,NAME) values ('EKA','EKAJUK');
Insert into CRB_LANGUAGE (CODE,NAME) values ('EL','GREEK, MODERN (POST 1453)');
Insert into CRB_LANGUAGE (CODE,NAME) values ('ELL','GREEK, MODERN (POST 1453)');
Insert into CRB_LANGUAGE (CODE,NAME) values ('ELX','ELAMITE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('EN','ENGLISH');
Insert into CRB_LANGUAGE (CODE,NAME) values ('ENG','ENGLISH');
Insert into CRB_LANGUAGE (CODE,NAME) values ('ENM','ENGLISH, MIDDLE (1100-1500)');
Insert into CRB_LANGUAGE (CODE,NAME) values ('EO','ESPERANTO');
Insert into CRB_LANGUAGE (CODE,NAME) values ('EPO','ESPERANTO');
Insert into CRB_LANGUAGE (CODE,NAME) values ('ES','SPANISH');
Insert into CRB_LANGUAGE (CODE,NAME) values ('EST','ESTONIAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('ET','ESTONIAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('ETH','ETHIOPIC');
Insert into CRB_LANGUAGE (CODE,NAME) values ('EU','BASQUE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('EUS','BASQUE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('EWE','EWE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('EWO','EWONDO');
Insert into CRB_LANGUAGE (CODE,NAME) values ('FA','PERSIAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('FAN','FANG');
Insert into CRB_LANGUAGE (CODE,NAME) values ('FAO','FAROESE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('FAS','PERSIAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('FAT','FANTI');
Insert into CRB_LANGUAGE (CODE,NAME) values ('FF','FULAH');
Insert into CRB_LANGUAGE (CODE,NAME) values ('FI','FINNISH');
Insert into CRB_LANGUAGE (CODE,NAME) values ('FIJ','FIJIAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('FIN','FINNISH');
Insert into CRB_LANGUAGE (CODE,NAME) values ('FIU','FINNO-UGRIAN (OTHER)');
Insert into CRB_LANGUAGE (CODE,NAME) values ('FJ','FIJIAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('FO','FAROESE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('FON','FON');
Insert into CRB_LANGUAGE (CODE,NAME) values ('FR','FRENCH');
Insert into CRB_LANGUAGE (CODE,NAME) values ('FRA','FRENCH');
Insert into CRB_LANGUAGE (CODE,NAME) values ('FRE','FRENCH');
Insert into CRB_LANGUAGE (CODE,NAME) values ('FRM','FRENCH, MIDDLE (CA. 1400-1600)');
Insert into CRB_LANGUAGE (CODE,NAME) values ('FRO','FRENCH, OLD (842-CA. 1400)');
Insert into CRB_LANGUAGE (CODE,NAME) values ('FRY','FRISIAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('FUL','FULAH');
Insert into CRB_LANGUAGE (CODE,NAME) values ('FUR','FRIULIAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('FY','FRISIAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('GA','IRISH');
Insert into CRB_LANGUAGE (CODE,NAME) values ('GAA','GA');
Insert into CRB_LANGUAGE (CODE,NAME) values ('GAY','GAYO');
Insert into CRB_LANGUAGE (CODE,NAME) values ('GBA','GBAYA');
Insert into CRB_LANGUAGE (CODE,NAME) values ('GD','GAELIC (SCOTS)');
Insert into CRB_LANGUAGE (CODE,NAME) values ('GEM','GERMANIC (OTHER)');
Insert into CRB_LANGUAGE (CODE,NAME) values ('GEO','GEORGIAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('GER','GERMAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('GEZ','GEEZ');
Insert into CRB_LANGUAGE (CODE,NAME) values ('GIL','GILBERTESE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('GL','GALLEGAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('GLA','GAELIC (SCOTS)');
Insert into CRB_LANGUAGE (CODE,NAME) values ('GLE','IRISH');
Insert into CRB_LANGUAGE (CODE,NAME) values ('GLG','GALLEGAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('GLV','MANX');
Insert into CRB_LANGUAGE (CODE,NAME) values ('GMH','GERMAN, MIDDLE HIGH (CA. 1050-1500)');
Insert into CRB_LANGUAGE (CODE,NAME) values ('GN','GUARANI');
Insert into CRB_LANGUAGE (CODE,NAME) values ('GOH','GERMAN, OLD HIGH (CA. 750-1050)');
Insert into CRB_LANGUAGE (CODE,NAME) values ('GON','GONDI');
Insert into CRB_LANGUAGE (CODE,NAME) values ('GOR','GORONTALO');
Insert into CRB_LANGUAGE (CODE,NAME) values ('GOT','GOTHIC');
Insert into CRB_LANGUAGE (CODE,NAME) values ('GRB','GREBO');
Insert into CRB_LANGUAGE (CODE,NAME) values ('GRC','GREEK, ANCIENT (TO 1453)');
Insert into CRB_LANGUAGE (CODE,NAME) values ('GRE','GREEK, MODERN (POST 1453)');
Insert into CRB_LANGUAGE (CODE,NAME) values ('GRN','GUARANI');
Insert into CRB_LANGUAGE (CODE,NAME) values ('GU','GUJARATI');
Insert into CRB_LANGUAGE (CODE,NAME) values ('GUJ','GUJARATI');
Insert into CRB_LANGUAGE (CODE,NAME) values ('GV','MANX');
Insert into CRB_LANGUAGE (CODE,NAME) values ('GWI','GWICH''IN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('HA','HAUSA');
Insert into CRB_LANGUAGE (CODE,NAME) values ('HAI','HAIDA');
Insert into CRB_LANGUAGE (CODE,NAME) values ('HAU','HAUSA');
Insert into CRB_LANGUAGE (CODE,NAME) values ('HAW','HAWAIIAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('HE','HEBREW');
Insert into CRB_LANGUAGE (CODE,NAME) values ('HEB','HEBREW');
Insert into CRB_LANGUAGE (CODE,NAME) values ('HER','HERERO');
Insert into CRB_LANGUAGE (CODE,NAME) values ('HI','HINDI');
Insert into CRB_LANGUAGE (CODE,NAME) values ('HIL','HILIGAYNON');
Insert into CRB_LANGUAGE (CODE,NAME) values ('HIM','HIMACHALI');
Insert into CRB_LANGUAGE (CODE,NAME) values ('HIN','HINDI');
Insert into CRB_LANGUAGE (CODE,NAME) values ('HIT','HITTITE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('HMN','HMONG');
Insert into CRB_LANGUAGE (CODE,NAME) values ('HMO','HIRI MOTU');
Insert into CRB_LANGUAGE (CODE,NAME) values ('HO','HIRI MOTU');
Insert into CRB_LANGUAGE (CODE,NAME) values ('HR','CROATIAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('HRV','CROATIAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('HT','HAITIAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('HU','HUNGARIAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('HUN','HUNGARIAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('HUP','HUPA');
Insert into CRB_LANGUAGE (CODE,NAME) values ('HY','ARMENIAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('HYE','ARMENIAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('HZ','HERERO');
Insert into CRB_LANGUAGE (CODE,NAME) values ('IA','INTERLINGUA (INTERNATIONAL AUXILARY LANGUAGE ASSOCIATION)');
Insert into CRB_LANGUAGE (CODE,NAME) values ('IBA','IBAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('IBO','IGBO');
Insert into CRB_LANGUAGE (CODE,NAME) values ('ICE','ICELANDIC');
Insert into CRB_LANGUAGE (CODE,NAME) values ('ID','INDONESIAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('IE','INTERLINGUE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('IG','IGBO');
Insert into CRB_LANGUAGE (CODE,NAME) values ('II','SICHUAN YI');
Insert into CRB_LANGUAGE (CODE,NAME) values ('IJO','IJO');
Insert into CRB_LANGUAGE (CODE,NAME) values ('IK','INUPIAK');
Insert into CRB_LANGUAGE (CODE,NAME) values ('IKU','INUKTITUT');
Insert into CRB_LANGUAGE (CODE,NAME) values ('ILE','INTERLINGUE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('ILO','ILOKO');
Insert into CRB_LANGUAGE (CODE,NAME) values ('INA','INTERLINGUA (INTERNATIONAL AUXILARY LANGUAGE ASSOCIATION)');
Insert into CRB_LANGUAGE (CODE,NAME) values ('INC','INDIC (OTHER)');
Insert into CRB_LANGUAGE (CODE,NAME) values ('IND','INDONESIAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('INE','INDO-EUROPEAN (OTHER)');
Insert into CRB_LANGUAGE (CODE,NAME) values ('IO','IDO');
Insert into CRB_LANGUAGE (CODE,NAME) values ('IPK','INUPIAK');
Insert into CRB_LANGUAGE (CODE,NAME) values ('IRA','IRANIAN (OTHER)');
Insert into CRB_LANGUAGE (CODE,NAME) values ('IRO','IROQUOIAN LANGUAGES');
Insert into CRB_LANGUAGE (CODE,NAME) values ('IS','ICELANDIC');
Insert into CRB_LANGUAGE (CODE,NAME) values ('ISL','ICELANDIC');
Insert into CRB_LANGUAGE (CODE,NAME) values ('IT','ITALIAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('ITA','ITALIAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('IU','INUKTITUT');
Insert into CRB_LANGUAGE (CODE,NAME) values ('JA','JAPANESE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('JAV','JAVANESE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('JAW','JAVANESE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('JPN','JAPANESE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('JPR','JUDEO-PERSIAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('JRB','JUDEO-ARABIC');
Insert into CRB_LANGUAGE (CODE,NAME) values ('JV','JAVANESE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('JW','JAVANESE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('KA','GEORGIAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('KAA','KARA-KALPAK');
Insert into CRB_LANGUAGE (CODE,NAME) values ('KAB','KABYLE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('KAC','KACHIN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('KAL','KALAALLISUT');
Insert into CRB_LANGUAGE (CODE,NAME) values ('KAM','KAMBA');
Insert into CRB_LANGUAGE (CODE,NAME) values ('KAN','KANNADA');
Insert into CRB_LANGUAGE (CODE,NAME) values ('KAR','KAREN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('KAS','KASHMIRI');
Insert into CRB_LANGUAGE (CODE,NAME) values ('KAT','GEORGIAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('KAU','KANURI');
Insert into CRB_LANGUAGE (CODE,NAME) values ('KAW','KAWI');
Insert into CRB_LANGUAGE (CODE,NAME) values ('KAZ','KAZAKH');
Insert into CRB_LANGUAGE (CODE,NAME) values ('KG','KONGO');
Insert into CRB_LANGUAGE (CODE,NAME) values ('KHA','KHASI');
Insert into CRB_LANGUAGE (CODE,NAME) values ('KHI','KHOISAN (OTHER)');
Insert into CRB_LANGUAGE (CODE,NAME) values ('KHM','KHMER');
Insert into CRB_LANGUAGE (CODE,NAME) values ('KHO','KHOTANESE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('KI','GIKUYU');
Insert into CRB_LANGUAGE (CODE,NAME) values ('KIK','KIKUYU');
Insert into CRB_LANGUAGE (CODE,NAME) values ('KIN','KINYARWANDA');
Insert into CRB_LANGUAGE (CODE,NAME) values ('KIR','KIRGHIZ');
Insert into CRB_LANGUAGE (CODE,NAME) values ('KJ','KWANYAMA');
Insert into CRB_LANGUAGE (CODE,NAME) values ('KK','KAZAKH');
Insert into CRB_LANGUAGE (CODE,NAME) values ('KL','KALAALLISUT');
Insert into CRB_LANGUAGE (CODE,NAME) values ('KM','KHMER');
Insert into CRB_LANGUAGE (CODE,NAME) values ('KMB','KIMBUNDU');
Insert into CRB_LANGUAGE (CODE,NAME) values ('KN','KANNADA');
Insert into CRB_LANGUAGE (CODE,NAME) values ('KO','KOREAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('KOK','KONKANI');
Insert into CRB_LANGUAGE (CODE,NAME) values ('KOM','KOMI');
Insert into CRB_LANGUAGE (CODE,NAME) values ('KON','KONGO');
Insert into CRB_LANGUAGE (CODE,NAME) values ('KOR','KOREAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('KOS','KOSRAEAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('KPE','KPELLE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('KR','KANURI');
Insert into CRB_LANGUAGE (CODE,NAME) values ('KRO','KRU');
Insert into CRB_LANGUAGE (CODE,NAME) values ('KRU','KURUKH');
Insert into CRB_LANGUAGE (CODE,NAME) values ('KS','KASHMIRI');
Insert into CRB_LANGUAGE (CODE,NAME) values ('KU','KURDISH');
Insert into CRB_LANGUAGE (CODE,NAME) values ('KUA','KUANYAMA');
Insert into CRB_LANGUAGE (CODE,NAME) values ('KUM','KUMYK');
Insert into CRB_LANGUAGE (CODE,NAME) values ('KUR','KURDISH');
Insert into CRB_LANGUAGE (CODE,NAME) values ('KUT','KUTENAI');
Insert into CRB_LANGUAGE (CODE,NAME) values ('KV','KOMI');
Insert into CRB_LANGUAGE (CODE,NAME) values ('KW','CORNISH');
Insert into CRB_LANGUAGE (CODE,NAME) values ('KY','KIRGHIZ');
Insert into CRB_LANGUAGE (CODE,NAME) values ('LA','LATIN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('LAD','LADINO');
Insert into CRB_LANGUAGE (CODE,NAME) values ('LAH','LAHNDA');
Insert into CRB_LANGUAGE (CODE,NAME) values ('LAM','LAMBA');
Insert into CRB_LANGUAGE (CODE,NAME) values ('LAO','LAO');
Insert into CRB_LANGUAGE (CODE,NAME) values ('LAT','LATIN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('LAV','LATVIAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('LB','LETZEBURGESCH');
Insert into CRB_LANGUAGE (CODE,NAME) values ('LEZ','LEZGHIAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('LG','GANDA');
Insert into CRB_LANGUAGE (CODE,NAME) values ('LI','LIMBURGISH');
Insert into CRB_LANGUAGE (CODE,NAME) values ('LIN','LINGALA');
Insert into CRB_LANGUAGE (CODE,NAME) values ('LIT','LITHUANIAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('LN','LINGALA');
Insert into CRB_LANGUAGE (CODE,NAME) values ('LO','LAO');
Insert into CRB_LANGUAGE (CODE,NAME) values ('LOL','MONGO');
Insert into CRB_LANGUAGE (CODE,NAME) values ('LOZ','LOZI');
Insert into CRB_LANGUAGE (CODE,NAME) values ('LT','LITHUANIAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('LTZ','LETZEBURGESCH');
Insert into CRB_LANGUAGE (CODE,NAME) values ('LU','LUBA-KATANGA');
Insert into CRB_LANGUAGE (CODE,NAME) values ('LUA','LUBA-LULUA');
Insert into CRB_LANGUAGE (CODE,NAME) values ('LUB','LUBA-KATANGA');
Insert into CRB_LANGUAGE (CODE,NAME) values ('LUG','GANDA');
Insert into CRB_LANGUAGE (CODE,NAME) values ('LUI','LUISENO');
Insert into CRB_LANGUAGE (CODE,NAME) values ('LUN','LUNDA');
Insert into CRB_LANGUAGE (CODE,NAME) values ('LUO','LUO (KENYA AND TANZANIA)');
Insert into CRB_LANGUAGE (CODE,NAME) values ('LUS','LUSHAI');
Insert into CRB_LANGUAGE (CODE,NAME) values ('LV','LATVIAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('MAC','MACEDONIAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('MAD','MADURESE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('MAG','MAGAHI');
Insert into CRB_LANGUAGE (CODE,NAME) values ('MAH','MARSHALL');
Insert into CRB_LANGUAGE (CODE,NAME) values ('MAI','MAITHILI');
Insert into CRB_LANGUAGE (CODE,NAME) values ('MAK','MAKASAR');
Insert into CRB_LANGUAGE (CODE,NAME) values ('MAL','MALAYALAM');
Insert into CRB_LANGUAGE (CODE,NAME) values ('MAN','MANDINGO');
Insert into CRB_LANGUAGE (CODE,NAME) values ('MAO','MAORI');
Insert into CRB_LANGUAGE (CODE,NAME) values ('MAP','AUSTRONESIAN (OTHER)');
Insert into CRB_LANGUAGE (CODE,NAME) values ('MAR','MARATHI');
Insert into CRB_LANGUAGE (CODE,NAME) values ('MAS','MASAI');
Insert into CRB_LANGUAGE (CODE,NAME) values ('MAY','MALAY');
Insert into CRB_LANGUAGE (CODE,NAME) values ('MDR','MANDAR');
Insert into CRB_LANGUAGE (CODE,NAME) values ('MEN','MENDE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('MG','MALAGASY');
Insert into CRB_LANGUAGE (CODE,NAME) values ('MGA','IRISH, MIDDLE (900-1200)');
Insert into CRB_LANGUAGE (CODE,NAME) values ('MH','MARSHALLESE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('MI','MAORI');
Insert into CRB_LANGUAGE (CODE,NAME) values ('MIC','MICMAC');
Insert into CRB_LANGUAGE (CODE,NAME) values ('MIN','MINANGKABAU');
Insert into CRB_LANGUAGE (CODE,NAME) values ('MIS','MISCELLANEOUS LANGUAGES');
Insert into CRB_LANGUAGE (CODE,NAME) values ('MK','MACEDONIAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('MKD','MACEDONIAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('MKH','MON-KHMER (OTHER)');
Insert into CRB_LANGUAGE (CODE,NAME) values ('ML','MALAYALAM');
Insert into CRB_LANGUAGE (CODE,NAME) values ('MLG','MALAGASY');
Insert into CRB_LANGUAGE (CODE,NAME) values ('MLT','MALTESE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('MN','MONGOLIAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('MNI','MANIPURI');
Insert into CRB_LANGUAGE (CODE,NAME) values ('MNO','MANOBO LANGUAGES');
Insert into CRB_LANGUAGE (CODE,NAME) values ('MO','MOLDAVIAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('MOH','MOHAWK');
Insert into CRB_LANGUAGE (CODE,NAME) values ('MOL','MOLDAVIAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('MON','MONGOLIAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('MOS','MOSSI');
Insert into CRB_LANGUAGE (CODE,NAME) values ('MR','MARATHI');
Insert into CRB_LANGUAGE (CODE,NAME) values ('MRI','MAORI');
Insert into CRB_LANGUAGE (CODE,NAME) values ('MS','MALAY');
Insert into CRB_LANGUAGE (CODE,NAME) values ('MSA','MALAY');
Insert into CRB_LANGUAGE (CODE,NAME) values ('MT','MALTESE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('MUL','MULTIPLE LANGUAGES');
Insert into CRB_LANGUAGE (CODE,NAME) values ('MUN','MUNDA LANGUAGES');
Insert into CRB_LANGUAGE (CODE,NAME) values ('MUS','CREEK');
Insert into CRB_LANGUAGE (CODE,NAME) values ('MWR','MARWARI');
Insert into CRB_LANGUAGE (CODE,NAME) values ('MY','BURMESE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('MYA','BURMESE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('MYN','MAYAN LANGUAGES');
Insert into CRB_LANGUAGE (CODE,NAME) values ('NA','NAURU');
Insert into CRB_LANGUAGE (CODE,NAME) values ('NAH','NAHUATL');
Insert into CRB_LANGUAGE (CODE,NAME) values ('NAI','NORTH AMERICAN INDIAN (OTHER)');
Insert into CRB_LANGUAGE (CODE,NAME) values ('NAU','NAURU');
Insert into CRB_LANGUAGE (CODE,NAME) values ('NAV','NAVAJO');
Insert into CRB_LANGUAGE (CODE,NAME) values ('NB','NORWEGIAN BOKMAL');
Insert into CRB_LANGUAGE (CODE,NAME) values ('NBL','NDEBELE, SOUTH');
Insert into CRB_LANGUAGE (CODE,NAME) values ('ND','NORTH NDEBELE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('NDE','NDEBELE, NORTH');
Insert into CRB_LANGUAGE (CODE,NAME) values ('NDO','NDONGA');
Insert into CRB_LANGUAGE (CODE,NAME) values ('NE','NEPALI');
Insert into CRB_LANGUAGE (CODE,NAME) values ('NEP','NEPALI');
Insert into CRB_LANGUAGE (CODE,NAME) values ('NEW','NEWARI');
Insert into CRB_LANGUAGE (CODE,NAME) values ('NG','NDONGA');
Insert into CRB_LANGUAGE (CODE,NAME) values ('NIA','NIAS');
Insert into CRB_LANGUAGE (CODE,NAME) values ('NIC','NIGER-KORDOFANIAN (OTHER)');
Insert into CRB_LANGUAGE (CODE,NAME) values ('NIU','NIUEAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('NL','DUTCH');
Insert into CRB_LANGUAGE (CODE,NAME) values ('NLD','DUTCH');
Insert into CRB_LANGUAGE (CODE,NAME) values ('NN','NORWEGIAN NYNORSK');
Insert into CRB_LANGUAGE (CODE,NAME) values ('NO','NORWEGIAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('NON','NORSE, OLD');
Insert into CRB_LANGUAGE (CODE,NAME) values ('NOR','NORWEGIAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('NR','SOUTH NDEBELE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('NSO','SOTHO, NORTHERN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('NUB','NUBIAN LANGUAGES');
Insert into CRB_LANGUAGE (CODE,NAME) values ('NV','NAVAJO');
Insert into CRB_LANGUAGE (CODE,NAME) values ('NY','CHICHEWA');
Insert into CRB_LANGUAGE (CODE,NAME) values ('NYA','NYANJA');
Insert into CRB_LANGUAGE (CODE,NAME) values ('NYM','NYAMWEZI');
Insert into CRB_LANGUAGE (CODE,NAME) values ('NYN','NYANKOLE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('NYO','NYORO');
Insert into CRB_LANGUAGE (CODE,NAME) values ('NZI','NZIMA');
Insert into CRB_LANGUAGE (CODE,NAME) values ('OC','OCCITAN (POST 1500)');
Insert into CRB_LANGUAGE (CODE,NAME) values ('OCI','OCCITAN (POST 1500)');
Insert into CRB_LANGUAGE (CODE,NAME) values ('OJ','OJIBWA');
Insert into CRB_LANGUAGE (CODE,NAME) values ('OJI','OJIBWA');
Insert into CRB_LANGUAGE (CODE,NAME) values ('OM','OROMO');
Insert into CRB_LANGUAGE (CODE,NAME) values ('OR','ORIYA');
Insert into CRB_LANGUAGE (CODE,NAME) values ('ORI','ORIYA');
Insert into CRB_LANGUAGE (CODE,NAME) values ('ORM','OROMO');
Insert into CRB_LANGUAGE (CODE,NAME) values ('OS','OSSETIAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('OSA','OSAGE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('OSS','OSSETIC');
Insert into CRB_LANGUAGE (CODE,NAME) values ('OTA','TURKISH, OTTOMAN (1500-1928)');
Insert into CRB_LANGUAGE (CODE,NAME) values ('OTO','OTOMIAN LANGUAGES');
Insert into CRB_LANGUAGE (CODE,NAME) values ('PA','PANJABI');
Insert into CRB_LANGUAGE (CODE,NAME) values ('PAA','PAPUAN (OTHER)');
Insert into CRB_LANGUAGE (CODE,NAME) values ('PAG','PANGASINAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('PAL','PAHLAVI');
Insert into CRB_LANGUAGE (CODE,NAME) values ('PAM','PAMPANGA');
Insert into CRB_LANGUAGE (CODE,NAME) values ('PAN','PANJABI');
Insert into CRB_LANGUAGE (CODE,NAME) values ('PAP','PAPIAMENTO');
Insert into CRB_LANGUAGE (CODE,NAME) values ('PAU','PALAUAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('PEO','PERSIAN, OLD (CA. 600-400 B.C.)');
Insert into CRB_LANGUAGE (CODE,NAME) values ('PER','PERSIAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('PHI','PHILIPPINE (OTHER)');
Insert into CRB_LANGUAGE (CODE,NAME) values ('PHN','PHOENICIAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('PI','PALI');
Insert into CRB_LANGUAGE (CODE,NAME) values ('PL','POLISH');
Insert into CRB_LANGUAGE (CODE,NAME) values ('PLI','PALI');
Insert into CRB_LANGUAGE (CODE,NAME) values ('POL','POLISH');
Insert into CRB_LANGUAGE (CODE,NAME) values ('PON','POHNPEIAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('POR','PORTUGUESE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('PRA','PRAKRIT LANGUAGES');
Insert into CRB_LANGUAGE (CODE,NAME) values ('PRO','PROVENCAL, OLD (TO 1500)');
Insert into CRB_LANGUAGE (CODE,NAME) values ('PS','PUSHTO');
Insert into CRB_LANGUAGE (CODE,NAME) values ('PT','PORTUGUESE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('PUS','PUSHTO');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QAA','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QAB','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QAC','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QAD','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QAE','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QAF','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QAG','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QAH','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QAI','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QAJ','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QAK','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QAL','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QAM','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QAN','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QAO','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QAP','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QAQ','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QAR','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QAS','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QAT','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QAU','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QAV','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QAW','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QAX','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QAY','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QAZ','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QBA','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QBB','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QBC','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QBD','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QBE','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QBF','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QBG','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QBH','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QBI','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QBJ','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QBK','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QBL','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QBM','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QBN','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QBO','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QBP','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QBQ','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QBR','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QBS','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QBT','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QBU','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QBV','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QBW','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QBX','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QBY','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QBZ','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QCA','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QCB','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QCC','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QCD','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QCE','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QCF','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QCG','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QCH','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QCI','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QCJ','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QCK','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QCL','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QCM','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QCN','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QCO','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QCP','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QCQ','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QCR','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QCS','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QCT','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QCU','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QCV','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QCW','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QCX','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QCY','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QCZ','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QDA','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QDB','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QDC','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QDD','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QDE','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QDF','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QDG','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QDH','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QDI','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QDJ','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QDK','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QDL','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QDM','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QDN','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QDO','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QDP','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QDQ','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QDR','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QDS','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QDT','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QDU','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QDV','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QDW','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QDX','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QDY','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QDZ','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QEA','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QEB','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QEC','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QED','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QEE','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QEF','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QEG','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QEH','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QEI','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QEJ','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QEK','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QEL','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QEM','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QEN','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QEO','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QEP','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QEQ','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QER','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QES','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QET','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QEU','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QEV','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QEW','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QEX','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QEY','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QEZ','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QFA','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QFB','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QFC','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QFD','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QFE','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QFF','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QFG','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QFH','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QFI','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QFJ','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QFK','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QFL','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QFM','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QFN','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QFO','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QFP','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QFQ','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QFR','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QFS','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QFT','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QFU','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QFV','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QFW','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QFX','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QFY','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QFZ','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QGA','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QGB','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QGC','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QGD','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QGE','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QGF','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QGG','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QGH','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QGI','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QGJ','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QGK','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QGL','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QGM','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QGN','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QGO','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QGP','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QGQ','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QGR','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QGS','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QGT','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QGU','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QGV','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QGW','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QGX','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QGY','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QGZ','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QHA','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QHB','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QHC','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QHD','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QHE','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QHF','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QHG','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QHH','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QHI','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QHJ','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QHK','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QHL','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QHM','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QHN','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QHO','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QHP','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QHQ','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QHR','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QHS','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QHT','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QHU','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QHV','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QHW','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QHX','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QHY','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QHZ','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QIA','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QIB','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QIC','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QID','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QIE','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QIF','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QIG','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QIH','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QII','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QIJ','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QIK','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QIL','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QIM','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QIN','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QIO','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QIP','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QIQ','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QIR','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QIS','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QIT','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QIU','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QIV','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QIW','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QIX','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QIY','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QIZ','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QJA','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QJB','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QJC','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QJD','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QJE','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QJF','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QJG','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QJH','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QJI','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QJJ','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QJK','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QJL','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QJM','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QJN','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QJO','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QJP','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QJQ','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QJR','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QJS','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QJT','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QJU','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QJV','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QJW','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QJX','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QJY','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QJZ','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QKA','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QKB','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QKC','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QKD','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QKE','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QKF','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QKG','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QKH','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QKI','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QKJ','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QKK','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QKL','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QKM','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QKN','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QKO','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QKP','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QKQ','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QKR','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QKS','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QKT','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QKU','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QKV','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QKW','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QKX','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QKY','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QKZ','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QLA','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QLB','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QLC','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QLD','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QLE','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QLF','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QLG','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QLH','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QLI','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QLJ','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QLK','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QLL','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QLM','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QLN','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QLO','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QLP','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QLQ','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QLR','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QLS','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QLT','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QLU','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QLV','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QLW','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QLX','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QLY','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QLZ','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QMA','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QMB','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QMC','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QMD','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QME','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QMF','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QMG','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QMH','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QMI','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QMJ','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QMK','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QML','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QMM','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QMN','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QMO','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QMP','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QMQ','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QMR','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QMS','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QMT','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QMU','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QMV','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QMW','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QMX','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QMY','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QMZ','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QNA','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QNB','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QNC','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QND','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QNE','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QNF','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QNG','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QNH','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QNI','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QNJ','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QNK','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QNL','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QNM','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QNN','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QNO','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QNP','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QNQ','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QNR','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QNS','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QNT','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QNU','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QNV','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QNW','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QNX','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QNY','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QNZ','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QOA','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QOB','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QOC','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QOD','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QOE','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QOF','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QOG','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QOH','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QOI','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QOJ','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QOK','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QOL','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QOM','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QON','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QOO','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QOP','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QOQ','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QOR','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QOS','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QOT','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QOU','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QOV','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QOW','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QOX','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QOY','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QOZ','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QPA','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QPB','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QPC','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QPD','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QPE','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QPF','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QPG','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QPH','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QPI','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QPJ','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QPK','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QPL','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QPM','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QPN','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QPO','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QPP','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QPQ','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QPR','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QPS','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QPT','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QPU','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QPV','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QPW','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QPX','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QPY','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QPZ','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QQA','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QQB','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QQC','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QQD','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QQE','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QQF','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QQG','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QQH','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QQI','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QQJ','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QQK','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QQL','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QQM','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QQN','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QQO','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QQP','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QQQ','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QQR','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QQS','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QQT','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QQU','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QQV','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QQW','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QQX','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QQY','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QQZ','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QRA','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QRB','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QRC','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QRD','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QRE','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QRF','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QRG','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QRH','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QRI','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QRJ','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QRK','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QRL','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QRM','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QRN','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QRO','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QRP','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QRQ','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QRR','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QRS','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QRT','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QRU','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QRV','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QRW','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QRX','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QRY','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QRZ','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QSA','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QSB','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QSC','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QSD','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QSE','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QSF','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QSG','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QSH','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QSI','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QSJ','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QSK','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QSL','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QSM','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QSN','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QSO','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QSP','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QSQ','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QSR','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QSS','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QST','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QSU','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QSV','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QSW','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QSX','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QSY','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QSZ','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QTA','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QTB','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QTC','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QTD','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QTE','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QTF','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QTG','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QTH','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QTI','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QTJ','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QTK','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QTL','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QTM','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QTN','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QTO','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QTP','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QTQ','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QTR','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QTS','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QTT','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QTU','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QTV','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QTW','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QTX','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QTY','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QTZ','RESERVED FOR LOCAL USE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QU','QUECHUA');
Insert into CRB_LANGUAGE (CODE,NAME) values ('QUE','QUECHUA');
Insert into CRB_LANGUAGE (CODE,NAME) values ('RAJ','RAJASTHANI');
Insert into CRB_LANGUAGE (CODE,NAME) values ('RAP','RAPANUI');
Insert into CRB_LANGUAGE (CODE,NAME) values ('RAR','RAROTONGAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('RM','RHAETO-ROMANCE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('RN','RUNDI');
Insert into CRB_LANGUAGE (CODE,NAME) values ('RO','ROMANIAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('ROA','ROMANCE (OTHER)');
Insert into CRB_LANGUAGE (CODE,NAME) values ('ROH','RHAETO-ROMANCE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('ROM','ROMANY');
Insert into CRB_LANGUAGE (CODE,NAME) values ('RON','ROMANIAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('RU','RUSSIAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('RUM','ROMANIAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('RUN','RUNDI');
Insert into CRB_LANGUAGE (CODE,NAME) values ('RUS','RUSSIAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('RW','KINYARWANDA');
Insert into CRB_LANGUAGE (CODE,NAME) values ('SA','SANSKRIT');
Insert into CRB_LANGUAGE (CODE,NAME) values ('SAD','SANDAWE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('SAG','SANGO');
Insert into CRB_LANGUAGE (CODE,NAME) values ('SAI','SOUTH AMERICAN INDIAN (OTHER)');
Insert into CRB_LANGUAGE (CODE,NAME) values ('SAL','SALISHAN LANGUAGES');
Insert into CRB_LANGUAGE (CODE,NAME) values ('SAM','SAMARITAN ARAMAIC');
Insert into CRB_LANGUAGE (CODE,NAME) values ('SAN','SANSKRIT');
Insert into CRB_LANGUAGE (CODE,NAME) values ('SAS','SASAK');
Insert into CRB_LANGUAGE (CODE,NAME) values ('SAT','SANTALI');
Insert into CRB_LANGUAGE (CODE,NAME) values ('SC','SARDINIAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('SCC','SERBIAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('SCO','SCOTS');
Insert into CRB_LANGUAGE (CODE,NAME) values ('SCR','CROATIAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('SD','SINDHI');
Insert into CRB_LANGUAGE (CODE,NAME) values ('SE','SAMI LANGUAGES');
Insert into CRB_LANGUAGE (CODE,NAME) values ('SEL','SELKUP');
Insert into CRB_LANGUAGE (CODE,NAME) values ('SEM','SEMITIC (OTHER)');
Insert into CRB_LANGUAGE (CODE,NAME) values ('SG','SANGO');
Insert into CRB_LANGUAGE (CODE,NAME) values ('SGA','IRISH, OLD (TO 900)');
Insert into CRB_LANGUAGE (CODE,NAME) values ('SH','SERBO-CROATIAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('SHN','SHAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('SI','SINHALESE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('SID','SIDAMO');
Insert into CRB_LANGUAGE (CODE,NAME) values ('SIN','SINHALESE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('SIO','SIOUAN LANGUAGES');
Insert into CRB_LANGUAGE (CODE,NAME) values ('SIT','SINO-TIBETAN (OTHER)');
Insert into CRB_LANGUAGE (CODE,NAME) values ('SK','SLOVAK');
Insert into CRB_LANGUAGE (CODE,NAME) values ('SL','SLOVENIAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('SLA','SLAVIC (OTHER)');
Insert into CRB_LANGUAGE (CODE,NAME) values ('SLK','SLOVAK');
Insert into CRB_LANGUAGE (CODE,NAME) values ('SLO','SLOVAK');
Insert into CRB_LANGUAGE (CODE,NAME) values ('SLV','SLOVENIAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('SM','SAMOAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('SMI','SAMI LANGUAGES');
Insert into CRB_LANGUAGE (CODE,NAME) values ('SMO','SAMOAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('SN','SHONA');
Insert into CRB_LANGUAGE (CODE,NAME) values ('SNA','SHONA');
Insert into CRB_LANGUAGE (CODE,NAME) values ('SND','SINDHI');
Insert into CRB_LANGUAGE (CODE,NAME) values ('SNK','SONINKE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('SO','SOMALI');
Insert into CRB_LANGUAGE (CODE,NAME) values ('SOG','SOGDIAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('SOM','SOMALI');
Insert into CRB_LANGUAGE (CODE,NAME) values ('SON','SONGHAI');
Insert into CRB_LANGUAGE (CODE,NAME) values ('SOT','SOTHO, SOUTHERN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('SPA','SPANISH');
Insert into CRB_LANGUAGE (CODE,NAME) values ('SQ','ALBANIAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('SQI','ALBANIAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('SR','SERBIAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('SRD','SARDINIAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('SRP','SERBIAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('SRR','SERER');
Insert into CRB_LANGUAGE (CODE,NAME) values ('SS','SWATI');
Insert into CRB_LANGUAGE (CODE,NAME) values ('SSA','NILO-SAHARAN (OTHER)');
Insert into CRB_LANGUAGE (CODE,NAME) values ('SSW','SWATI');
Insert into CRB_LANGUAGE (CODE,NAME) values ('ST','SOTHO, SOUTHERN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('SU','SUNDANESE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('SUK','SUKUMA');
Insert into CRB_LANGUAGE (CODE,NAME) values ('SUN','SUNDANESE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('SUS','SUSU');
Insert into CRB_LANGUAGE (CODE,NAME) values ('SUX','SUMERIAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('SV','SWEDISH');
Insert into CRB_LANGUAGE (CODE,NAME) values ('SW','SWAHILI');
Insert into CRB_LANGUAGE (CODE,NAME) values ('SWA','SWAHILI');
Insert into CRB_LANGUAGE (CODE,NAME) values ('SWE','SWEDISH');
Insert into CRB_LANGUAGE (CODE,NAME) values ('SYR','SYRIAC');
Insert into CRB_LANGUAGE (CODE,NAME) values ('TA','TAMIL');
Insert into CRB_LANGUAGE (CODE,NAME) values ('TAH','TAHITIAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('TAI','TAI (OTHER)');
Insert into CRB_LANGUAGE (CODE,NAME) values ('TAM','TAMIL');
Insert into CRB_LANGUAGE (CODE,NAME) values ('TAT','TATAR');
Insert into CRB_LANGUAGE (CODE,NAME) values ('TE','TELUGU');
Insert into CRB_LANGUAGE (CODE,NAME) values ('TEL','TELUGU');
Insert into CRB_LANGUAGE (CODE,NAME) values ('TEM','TIMNE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('TER','TERENO');
Insert into CRB_LANGUAGE (CODE,NAME) values ('TET','TETUM');
Insert into CRB_LANGUAGE (CODE,NAME) values ('TG','TAJIK');
Insert into CRB_LANGUAGE (CODE,NAME) values ('TGK','TAJIK');
Insert into CRB_LANGUAGE (CODE,NAME) values ('TGL','TAGALOG');
Insert into CRB_LANGUAGE (CODE,NAME) values ('TH','THAI');
Insert into CRB_LANGUAGE (CODE,NAME) values ('THA','THAI');
Insert into CRB_LANGUAGE (CODE,NAME) values ('TI','TIGRINYA');
Insert into CRB_LANGUAGE (CODE,NAME) values ('TIB','TIBETAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('TIG','TIGRE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('TIR','TIGRINYA');
Insert into CRB_LANGUAGE (CODE,NAME) values ('TIV','TIV');
Insert into CRB_LANGUAGE (CODE,NAME) values ('TK','TURKMEN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('TKL','TOKELAU');
Insert into CRB_LANGUAGE (CODE,NAME) values ('TL','TAGALOG');
Insert into CRB_LANGUAGE (CODE,NAME) values ('TLI','TLINGIT');
Insert into CRB_LANGUAGE (CODE,NAME) values ('TMH','TAMASHEK');
Insert into CRB_LANGUAGE (CODE,NAME) values ('TN','TSWANA');
Insert into CRB_LANGUAGE (CODE,NAME) values ('TO','TONGA');
Insert into CRB_LANGUAGE (CODE,NAME) values ('TOG','TONGA (NYASA)');
Insert into CRB_LANGUAGE (CODE,NAME) values ('TON','TONGA (TONGA ISLANDS)');
Insert into CRB_LANGUAGE (CODE,NAME) values ('TPI','TOK PISIN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('TR','TURKISH');
Insert into CRB_LANGUAGE (CODE,NAME) values ('TS','TSONGA');
Insert into CRB_LANGUAGE (CODE,NAME) values ('TSI','TSIMSHIAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('TSN','TSWANA');
Insert into CRB_LANGUAGE (CODE,NAME) values ('TSO','TSONGA');
Insert into CRB_LANGUAGE (CODE,NAME) values ('TT','TATAR');
Insert into CRB_LANGUAGE (CODE,NAME) values ('TUK','TURKMEN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('TUM','TUMBUKA');
Insert into CRB_LANGUAGE (CODE,NAME) values ('TUR','TURKISH');
Insert into CRB_LANGUAGE (CODE,NAME) values ('TUT','ALTAIC (OTHER)');
Insert into CRB_LANGUAGE (CODE,NAME) values ('TVL','TUVALU');
Insert into CRB_LANGUAGE (CODE,NAME) values ('TW','TWI');
Insert into CRB_LANGUAGE (CODE,NAME) values ('TWI','TWI');
Insert into CRB_LANGUAGE (CODE,NAME) values ('TY','TAHITIAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('TYV','TUVINIAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('UG','UIGHUR');
Insert into CRB_LANGUAGE (CODE,NAME) values ('UGA','UGARITIC');
Insert into CRB_LANGUAGE (CODE,NAME) values ('UIG','UIGHUR');
Insert into CRB_LANGUAGE (CODE,NAME) values ('UK','UKRAINIAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('UKR','UKRAINIAN');
Insert into CRB_LANGUAGE (CODE,NAME) values ('UMB','UMBUNDU');
Insert into CRB_LANGUAGE (CODE,NAME) values ('UND','UNDETERMINED');
Insert into CRB_LANGUAGE (CODE,NAME) values ('UR','URDU');
Insert into CRB_LANGUAGE (CODE,NAME) values ('URD','URDU');
Insert into CRB_LANGUAGE (CODE,NAME) values ('UZ','UZBEK');
Insert into CRB_LANGUAGE (CODE,NAME) values ('UZB','UZBEK');
Insert into CRB_LANGUAGE (CODE,NAME) values ('VAI','VAI');
Insert into CRB_LANGUAGE (CODE,NAME) values ('VE','VENDA');
Insert into CRB_LANGUAGE (CODE,NAME) values ('VEN','VENDA');
Insert into CRB_LANGUAGE (CODE,NAME) values ('VI','VIETNAMESE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('VIE','VIETNAMESE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('VO','VOLAPUK');
Insert into CRB_LANGUAGE (CODE,NAME) values ('VOL','VOLAPUK');
Insert into CRB_LANGUAGE (CODE,NAME) values ('VOT','VOTIC');
Insert into CRB_LANGUAGE (CODE,NAME) values ('WA','WALLOON');
Insert into CRB_LANGUAGE (CODE,NAME) values ('WAK','WAKASHAN LANGUAGES');
Insert into CRB_LANGUAGE (CODE,NAME) values ('WAL','WALAMO');
Insert into CRB_LANGUAGE (CODE,NAME) values ('WAR','WARAY');
Insert into CRB_LANGUAGE (CODE,NAME) values ('WAS','WASHO');
Insert into CRB_LANGUAGE (CODE,NAME) values ('WEL','WELSH');
Insert into CRB_LANGUAGE (CODE,NAME) values ('WEN','SORBIAN LANGUAGES');
Insert into CRB_LANGUAGE (CODE,NAME) values ('WO','WOLOF');
Insert into CRB_LANGUAGE (CODE,NAME) values ('WOL','WOLOF');
Insert into CRB_LANGUAGE (CODE,NAME) values ('XH','XHOSA');
Insert into CRB_LANGUAGE (CODE,NAME) values ('XHO','XHOSA');
Insert into CRB_LANGUAGE (CODE,NAME) values ('YAO','YAO');
Insert into CRB_LANGUAGE (CODE,NAME) values ('YAP','YAPESE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('YI','YIDDISH');
Insert into CRB_LANGUAGE (CODE,NAME) values ('YID','YIDDISH');
Insert into CRB_LANGUAGE (CODE,NAME) values ('YO','YORUBA');
Insert into CRB_LANGUAGE (CODE,NAME) values ('YOR','YORUBA');
Insert into CRB_LANGUAGE (CODE,NAME) values ('YPK','YUPIK LANGUAGES');
Insert into CRB_LANGUAGE (CODE,NAME) values ('ZA','ZHUANG');
Insert into CRB_LANGUAGE (CODE,NAME) values ('ZAP','ZAPOTEC');
Insert into CRB_LANGUAGE (CODE,NAME) values ('ZEN','ZENAGA');
Insert into CRB_LANGUAGE (CODE,NAME) values ('ZH','CHINESE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('ZHA','ZHUANG');
Insert into CRB_LANGUAGE (CODE,NAME) values ('ZHO','CHINESE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('ZND','ZANDE');
Insert into CRB_LANGUAGE (CODE,NAME) values ('ZU','ZULU');
Insert into CRB_LANGUAGE (CODE,NAME) values ('ZUL','ZULU');
Insert into CRB_LANGUAGE (CODE,NAME) values ('ZUN','ZUNI');
