CREATE TABLE CRB_NEW_TIME_ZONE 
   (	TZ_GROUP VARCHAR(3), 
	REL_COUNTRY_CODE VARCHAR(2) NOT NULL , 
	YEAR VARCHAR(4) NOT NULL , 
	DIFFER_GMT INT NOT NULL , 
	DIFFER_SIGN VARCHAR(1) NOT NULL , 
	DAYLIGHT_SAVINGS INT NOT NULL , 
	ED DATE, 
	DD DATE, 
	ED_STATUS VARCHAR(1) DEFAULT 'U' NOT NULL , 
	DD_STATUS VARCHAR(1) DEFAULT 'U' NOT NULL , 
	HEMISPHERE VARCHAR(1),
	UNIQUE KEY(TZ_GROUP,REL_COUNTRY_CODE,YEAR),
	KEY(REL_COUNTRY_CODE)
   ) 
--  ALTER TABLE CRB_NEW_TIME_ZONE ADD CONSTRAINT CRB_UN_NTZ_KEY UNIQUE (TZ_GROUP, REL_COUNTRY_CODE, YEAR) 
--  ALTER TABLE CRB_NEW_TIME_ZONE ADD CONSTRAINT CRB_CHK_NTZ_GROUP CHECK (LENGTH(tz_group) < 4 AND UPPER(tz_group) = tz_group) 
--  ALTER TABLE CRB_NEW_TIME_ZONE ADD CONSTRAINT CRB_CHK_NTZ_YEAR CHECK ( LENGTH(year) = 4 ) 
--  ALTER TABLE CRB_NEW_TIME_ZONE ADD CONSTRAINT CRB_CHK_NTZ_GMT CHECK (differ_GMT < 99) 
--  ALTER TABLE CRB_NEW_TIME_ZONE ADD CONSTRAINT CRB_CHK_NTZ_DSA CHECK (daylight_savings < 99) 
--  ALTER TABLE CRB_NEW_TIME_ZONE ADD CONSTRAINT CRB_CHK_NTZ_SIGN CHECK (LENGTH(differ_sign) = 1 AND differ_sign IN ('P','N')) 
-- ALTER TABLE CRB_NEW_TIME_ZONE ADD CONSTRAINT CRB_CHK_NTZ_HEMISPHERE CHECK (LENGTH(hemisphere) = 1 AND hemisphere IN ('N','S')) 
-- ALTER TABLE CRB_NEW_TIME_ZONE ADD CONSTRAINT CRB_FK_NTZ_COUNTRY FOREIGN KEY (REL_COUNTRY_CODE)
--	  REFERENCES CRB_COUNTRY (CODE) 
 

--  CREATE INDEX CRB_IDX_NTZ_COUNTRY ON CRB_NEW_TIME_ZONE (REL_COUNTRY_CODE) 
  
 
--  CREATE UNIQUE INDEX CRB_IDX_NTZ_KEY ON CRB_NEW_TIME_ZONE (TZ_GROUP, REL_COUNTRY_CODE, YEAR) 
  