--
-- crb_airline
--
  CREATE TABLE CRB_AIRLINE (	
	CODE VARCHAR(3) NOT NULL, 
	OLD_CODE VARCHAR(2) NOT NULL, 
	NEW_CODE VARCHAR(3), 
	NAME VARCHAR(32) NOT NULL, 
	TICKETING_NAME VARCHAR(24), 
	NUM_CODE SMALLINT UNSIGNED, 
	PRIMARY KEY(CODE) 
);
