
  CREATE TABLE CRB_REGION 
   (	CODE VARCHAR(5) NOT NULL , 
	NAME VARCHAR(20) NOT NULL ,
PRIMARY KEY(CODE)
   ) 
  -- ALTER TABLE CRB_REGION ADD CONSTRAINT CRB_UNIQ_RE_CODE UNIQUE (CODE) 
  -- ALTER TABLE CRB_REGION ADD CONSTRAINT CRB_CHK_RE_CODE CHECK ( ((LENGTH(code) = 5) OR (LENGTH(code) = 4))
	 		--  AND (UPPER(code) = code)) 
 

--  CREATE UNIQUE INDEX CRB_IDX_RE_CODE ON CRB_REGION (CODE) 
  
 
