
  CREATE TABLE CRB_STATE 
   (	
    THEKEY VARCHAR(5) NOT NULL , 
	STATE_CODE VARCHAR(3), 
	STATE_NAME VARCHAR(30), 
	COUNTRY_CODE VARCHAR(2) NOT NULL , 
	REL_REGION_CODE VARCHAR(5) NOT NULL , 
	REL_CONTINENT_CODE VARCHAR(4) NOT NULL ,
	PRIMARY KEY(THEKEY),
	KEY(REL_CONTINENT_CODE,COUNTRY_CODE,REL_REGION_CODE)
   ) 
  -- ALTER TABLE CRB_STATE ADD CONSTRAINT CRB_UN_ST_KEY UNIQUE (KEY) 
  -- ALTER TABLE CRB_STATE ADD CONSTRAINT CRB_CHK_ST_KEY CHECK ( LENGTH(key) > 1 AND LENGTH(key) < 6 AND UPPER(key) = key) 
  -- ALTER TABLE CRB_STATE ADD CONSTRAINT CRB_CHK_ST_STATE CHECK (LENGTH(state_code) < 4 AND UPPER(state_code) = state_code) 
  -- ALTER TABLE CRB_STATE ADD CONSTRAINT CRB_CHK_ST_COUNTRY CHECK (LENGTH(country_code) = 2 AND UPPER(country_code) = country_code) 
  -- ALTER TABLE CRB_STATE ADD CONSTRAINT CRB_FK_ST_CONT FOREIGN KEY (REL_CONTINENT_CODE)
	-- REFERENCES CRB_CONTINENT (CODE) 
  -- ALTER TABLE CRB_STATE ADD CONSTRAINT CRB_FK_ST_REGION FOREIGN KEY (REL_REGION_CODE)
	--  REFERENCES CRB_REGION (CODE) 
 

--  CREATE INDEX CRB_IDX_ST_CONT ON CRB_STATE (REL_CONTINENT_CODE) 
  
 
--  CREATE INDEX CRB_IDX_ST_COUNTRY ON CRB_STATE (COUNTRY_CODE) 
  
 
--  CREATE UNIQUE INDEX CRB_IDX_ST_KEY ON CRB_STATE (THEKEY) 
  
 
--  CREATE INDEX CRB_IDX_ST_REGION ON CRB_STATE (REL_REGION_CODE) 
  
 
