
  CREATE TABLE CRB_ISO_COUNTRY 
   (	
   	ISO_CODE VARCHAR(3) NOT NULL , 
	IATA_CODE VARCHAR(2) NOT NULL,
	PRIMARY KEY(ISO_CODE, IATA_CODE) 
   ) 
--  ALTER TABLE CRB_ISO_COUNTRY ADD CONSTRAINT CRB_UNIQ_ISO_CT_ISO_CODE UNIQUE (ISO_CODE) 
--  ALTER TABLE CRB_ISO_COUNTRY ADD CONSTRAINT CRB_CHK_ISO_CT_ISO_CODE CHECK ((LENGTH(iso_code) = 3) AND (UPPER(iso_code) = iso_code)) 
--  ALTER TABLE CRB_ISO_COUNTRY ADD CONSTRAINT CRB_CHK_ISO_CT_IATA_CODE CHECK ((LENGTH(iata_code) = 2) AND (UPPER(iata_code) = iata_code)) 
--  ALTER TABLE CRB_ISO_COUNTRY ADD CONSTRAINT CRB_FK_ISO_CT_COUNTRY_CODE FOREIGN KEY (IATA_CODE)
--	  REFERENCES CRB_COUNTRY (CODE) 
 

--  CREATE UNIQUE INDEX CRB_IDX_ISO_CT_CODE ON CRB_ISO_COUNTRY (ISO_CODE) 
  
 
--  CREATE UNIQUE INDEX CRB_IDX_ISO_CT_IATA_CODE ON CRB_ISO_COUNTRY (IATA_CODE) 
  
 
