
  CREATE TABLE CRB_COUNTRY 
   (	
    CODE VARCHAR(2) NOT NULL , 
	NAME VARCHAR(30) NOT NULL , 
	REL_REGION_CODE VARCHAR(5) NOT NULL , 
	REL_CONTINENT_CODE VARCHAR(4) NOT NULL , 
	SELLING_CURRENCY VARCHAR(3) NOT NULL , 
	LOCAL_CURRENCY VARCHAR(3),
	PRIMARY KEY(CODE),
	KEY(REL_CONTINENT_CODE,REL_REGION_CODE)
   ) 
  
 
