
  CREATE TABLE CRB_LANGUAGE 
   (	CODE VARCHAR(3) NOT NULL , 
	NAME VARCHAR(60) NOT NULL ,
	PRIMARY KEY(CODE)
   ) 
--  ALTER TABLE CRB_LANGUAGE ADD CONSTRAINT CRB_UNIQ_LG_CODE UNIQUE (CODE) 
--  ALTER TABLE CRB_LANGUAGE ADD CONSTRAINT CRB_CHK_LA_CODE CHECK ( ((LENGTH(code) = 3) OR (LENGTH(code) = 2))
--	 		  AND (UPPER(code) = code) ) 
 

--  CREATE UNIQUE INDEX CRB_IDX_LG_CODE ON CRB_LANGUAGE (CODE) 
  
 
