
  CREATE TABLE CRB_ISO_CURRENCY 
   (	ISO_CODE VARCHAR(3) NOT NULL , 
	ISO_DEC_POS INT, 
	IATA_CODE VARCHAR(3) NOT NULL ,
	PRIMARY KEY(IATA_CODE, ISO_CODE)
   ) 
--  ALTER TABLE CRB_ISO_CURRENCY ADD CONSTRAINT CRB_UNIQ_ISO_CU_ISO_CODE UNIQUE (ISO_CODE) 
--  ALTER TABLE CRB_ISO_CURRENCY ADD CONSTRAINT CRB_CHK_ISO_CU_ISO_CODE CHECK ((LENGTH(iso_code) = 3) AND (UPPER(iso_code) = iso_code)) 
--  ALTER TABLE CRB_ISO_CURRENCY ADD CONSTRAINT CRB_CHK_ISO_CU_IATA_CODE CHECK ((LENGTH(iata_code) = 3) AND (UPPER(iata_code) = iata_code)) 
--  ALTER TABLE CRB_ISO_CURRENCY ADD CONSTRAINT RFD_FK_ISO_CU_CURRENCY_CODE FOREIGN KEY (IATA_CODE)
--	  REFERENCES CRB_CURRENCY (CODE) 
 

--  CREATE UNIQUE INDEX CRB_IDX_ISO_CU_IATA_CODE ON CRB_ISO_CURRENCY (IATA_CODE) 
  
 
--  CREATE UNIQUE INDEX CRB_IDX_ISO_CU_ISO_CODE ON CRB_ISO_CURRENCY (ISO_CODE) 
  
 
