--
-- crb_airport_terminal
--
  CREATE TABLE CRB_AIRPORT_TERMINAL (	
    AIRPORT_CODE VARCHAR(3) NOT NULL, 
	TERMINAL_CODE VARCHAR(2) NOT NULL, 
	TERMINAL_NAME VARCHAR(100) NOT NULL,
	PRIMARY KEY (AIRPORT_CODE, TERMINAL_CODE)
   );

--  ALTER TABLE CRB_AIRPORT_TERMINAL ADD CONSTRAINT CRB_UNIQ_AT_TERMINAL UNIQUE (AIRPORT_CODE, TERMINAL_CODE)
--  ALTER TABLE CRB_AIRPORT_TERMINAL ADD CONSTRAINT CRB_CHK_AT_CODE CHECK (LENGTH(airport_code) = 3 AND UPPER(airport_code) = airport_code)
--  ALTER TABLE CRB_AIRPORT_TERMINAL ADD CONSTRAINT CRB_FK_AT_AIRPORT FOREIGN KEY (AIRPORT_CODE) REFERENCES CRB_CITY (CODE)
 
--  CREATE UNIQUE INDEX CRB_IDX_AT_TERMINAL ON CRB_AIRPORT_TERMINAL (AIRPORT_CODE, TERMINAL_CODE) 