
CREATE TABLE IF NOT EXISTS CRB_CITY
(
  CODE VARCHAR(3) NOT NULL,
  TICKETING_NAME VARCHAR(18) NOT NULL,
  TELETICKETING_NAME VARCHAR(16) NOT NULL,
  EXTENDED_NAME VARCHAR(30) NOT NULL,
  CITY_NAME VARCHAR(30) NOT NULL,
  REL_CITY_CODE VARCHAR(3) NOT NULL,
  IS_AIRPORT VARCHAR(1) NOT NULL,
  STATE_CODE VARCHAR(3),
  REL_COUNTRY_CODE VARCHAR(2) NOT NULL,
  REL_REGION_CODE VARCHAR(5) NOT NULL,
  REL_CONTINENT_CODE VARCHAR(4) NOT NULL,
  REL_TIME_ZONE_GRP VARCHAR(5) NOT NULL,
  LONGITUDE FLOAT(20),
  LATITUDE FLOAT(20),
  NUMERIC_CODE INTEGER,
  IS_COMMERCIAL VARCHAR(1) NOT NULL, 
  PRIMARY KEY (CODE),
  KEY `GEOGRAPHICAL CODES`(REL_CITY_CODE,REL_CONTINENT_CODE,REL_COUNTRY_CODE,REL_REGION_CODE,REL_TIME_ZONE_GRP)
);

